# Generated by Django 4.1.7 on 2023-02-18 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_insta', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Insta_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('name_ruby', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('post', models.CharField(blank=True, max_length=10)),
                ('prefectures', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('insta_id', models.CharField(blank=True, max_length=255)),
                ('insta_pass', models.CharField(blank=True, max_length=255)),
                ('insta_plan', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='申込日')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hp_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new', models.BooleanField(blank=True, null=True)),
                ('site_url', models.URLField(blank=True)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('manager_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('post', models.CharField(blank=True, max_length=10)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('company_overview', models.TextField(blank=True)),
                ('hope_domain', models.CharField(blank=True, max_length=255)),
                ('site_image', models.CharField(blank=True, choices=[('kind', '優しい'), ('warm', '暖かい'), ('lively', 'にぎやか'), ('calm', '落ち着きのある'), ('japanese_style', '和風'), ('deluxe', '高級な'), ('others', 'その他')], max_length=50)),
                ('site_image_text', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, choices=[('red', '赤'), ('blue', '青'), ('green', '緑'), ('black', '黒'), ('White', '白'), ('pink', 'ピンク'), ('orange', 'オレンジ'), ('others', 'その他')], max_length=50)),
                ('color_text', models.TextField(blank=True)),
                ('business', models.TextField(blank=True)),
                ('menu', models.TextField(blank=True)),
                ('strength', models.TextField(blank=True)),
                ('keyword', models.TextField(blank=True)),
                ('image_data', models.FileField(blank=True, null=True, upload_to='')),
                ('hp_plan', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='申込日')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_token', models.TextField(blank=True)),
                ('customer_id', models.TextField(blank=True)),
                ('sub_id', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
